/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_package;

import java.awt.Color;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.rtf.RTFEditorKit;

/**
 *
 * @author Tomaz Lunder
 */
public class MainJFrame extends javax.swing.JFrame {

    final private String OBVESTILA = "Obvestila: ";
    private ArrayList<Integer> selected;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        selected = new ArrayList<>();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jSeparator3 = new javax.swing.JSeparator();
        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDatotekaOdpri = new javax.swing.JMenuItem();
        jMenuItemDatotekaShrani = new javax.swing.JMenuItem();
        jMenuItemDatotekaIzhod = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBounds(new java.awt.Rectangle(400, 400, 350, 150));
        jDialog1.setPreferredSize(new java.awt.Dimension(350, 150));

        jLabel4.setText("Želite datoteko shraniti?");

        jButton5.setText("Shrani");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShraniAP(evt);
            }
        });

        jButton6.setText("Prekliči");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogPrekliciAP(evt);
            }
        });

        jButton7.setText("Izhod");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogIzhodAP(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 800));

        jToolBar1.setRollover(true);

        jButton1.setText("Odpri");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdpriAP(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setText("Shrani");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShraniAP(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton3.setText("Najdi vse");
        jButton3.setToolTipText("");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNajdiAP(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator4);

        jButton4.setText("Papajščina");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPapajščinaAP(evt);
            }
        });
        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane2KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Obvestila: ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setDisplayedMnemonic('I');
        jLabel2.setText("Iskanje:");

        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClear(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(jButton8))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setMnemonic('D');
        jMenu1.setText("Datoteka");

        jMenuItemDatotekaOdpri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDatotekaOdpri.setMnemonic('O');
        jMenuItemDatotekaOdpri.setText("Odpri");
        jMenuItemDatotekaOdpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdpriAP(evt);
            }
        });
        jMenu1.add(jMenuItemDatotekaOdpri);

        jMenuItemDatotekaShrani.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDatotekaShrani.setMnemonic('S');
        jMenuItemDatotekaShrani.setText("Shrani");
        jMenuItemDatotekaShrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShraniAP(evt);
            }
        });
        jMenu1.add(jMenuItemDatotekaShrani);

        jMenuItemDatotekaIzhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDatotekaIzhod.setMnemonic('I');
        jMenuItemDatotekaIzhod.setText("Izhod");
        jMenuItemDatotekaIzhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIzhod(evt);
            }
        });
        jMenu1.add(jMenuItemDatotekaIzhod);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('I');
        jMenu2.setText("Iskanje");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setMnemonic('N');
        jMenuItem4.setText("Najdi vse");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNajdiAP(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setMnemonic('P');
        jMenuItem5.setText("Papajščina");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPapajščinaAP(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('B');
        jMenu3.setText("Barve");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setMnemonic('B');
        jMenuItem6.setText("Besedilo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBarvaBesedilaAP(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setMnemonic('O');
        jMenuItem7.setText("Ozadje");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBarvaOzadjaAP(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('P');
        jMenu4.setText("Pomoč");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setMnemonic('A');
        jMenuItem8.setText("Avtor");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAvtorAP(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOdpriAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdpriAP
        jTextPane2.select(0, jTextPane2.getText().length());
        barvajIzbrano(Color.WHITE, true);
        barvajIzbrano(Color.BLACK, false);
        clearSelection();
        jLabel3.setText("");
        jTextPane2.setEditable(true);
        
        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser.getSelectedFile();
            try {
                jLabel1.setText(OBVESTILA + "Odprta datoteka- " + f.getName() + ", Velikost-" + f.length() + "B");
                jTextPane2.read(new FileReader(f), null);
            } catch (Exception e) {
                jLabel1.setText("Napaka pri branju datoteke " + f.getName());
            }
        }

    }//GEN-LAST:event_jMenuItemOdpriAP

    private void jMenuItemShraniAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShraniAP
        if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser.getSelectedFile();
            try {
                jLabel1.setText(OBVESTILA + "Shranjena datoteka- " + f.getName());
                jTextPane2.write(new FileWriter(f));
            } catch (Exception e) {
                jLabel1.setText(OBVESTILA + "Napaka pri pisanju datoteke-" + f.getName());
            }
        }
    }//GEN-LAST:event_jMenuItemShraniAP

    private void jMenuBarvaBesedilaAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBarvaBesedilaAP
        Color c = JColorChooser.showDialog(this, "Izberi barvo besedila", Color.black);
        barvajIzbrano(c, false);
    }//GEN-LAST:event_jMenuBarvaBesedilaAP

    private void jMenuBarvaOzadjaAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBarvaOzadjaAP
        Color c = JColorChooser.showDialog(this, "Izberi barvo besedila", Color.black);
        barvajIzbrano(c, true);
    }//GEN-LAST:event_jMenuBarvaOzadjaAP

    private void jMenuItemAvtorAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAvtorAP
        jLabel1.setText(OBVESTILA + "Avtor-Tomaž Lunder, Kontakt:-tomazlunder1@gmail.com");
    }//GEN-LAST:event_jMenuItemAvtorAP

    private void clearSelection() {
        StyleContext context = new StyleContext();
        Style style = context.addStyle("mystyle", null);
        StyleConstants.setBackground(style, Color.WHITE);
        StyleConstants.setForeground(style, Color.BLACK);
        for (int i = 0; i < selected.size(); i += 2) {
            jTextPane2.select(selected.get(i), selected.get(i + 1));
            jTextPane2.setCharacterAttributes(style, true);
        }

        selected = new ArrayList<>();
        jTextPane2.setEditable(true);

    }

    private void jMenuItemNajdiAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNajdiAP

        clearSelection();

        String isci = jTextField1.getText();
        String text = jTextPane2.getText();

        if (isci.length() == 0) {
            return;
        }

        int pojavitev = 0;
        int add = 0;

        Scanner sc = new Scanner(text);
        while(sc.hasNextLine()){
            int index = 0;
            String line = sc.nextLine();
            while (true) {
                int found = line.indexOf(isci, index);
                if (found != -1) {
                    pojavitev++;
                    jTextPane2.select(found + add, found + isci.length() + add);
                    index = found + isci.length();
                    barvajIzbrano(Color.YELLOW, true);
                    selected.add(found + add);
                    selected.add(found + isci.length() + add);
                    
                }
                if (found == -1) {
                    break;
                }
            }
            add+=line.length()+1;
        }
        
        jLabel3.setText("Najdenih " + pojavitev + " pojavitev");
        if(pojavitev > 0){
            jTextPane2.grabFocus();
            jTextPane2.moveCaretPosition(selected.get(0));
            jTextPane2.select(selected.get(0), selected.get(0));
            
            jTextPane2.setEditable(false);
            jTextPane2.getCaret().setVisible(true);
            
            jLabel1.setText(OBVESTILA + "Klikni gumb X za nadaljevanje urejanja.");
            
        }
        
        //if(pojavitev > 0) jTextPane2.setEditable(false);

        //jTextPane2.grabFocus();
        //jTextPane2.moveCaretPosition(i);
    }//GEN-LAST:event_jMenuItemNajdiAP

    private void jBtnClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClear
        clearSelection();
        jLabel3.setText("Od-označil iskane besede.");
        jLabel1.setText(OBVESTILA + "");
    }//GEN-LAST:event_jBtnClear

    private void jMenuItemIzhod(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIzhod
        jDialog1.setVisible(true);
                
    }//GEN-LAST:event_jMenuItemIzhod

    private void jMenuItemPapajščinaAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPapajščinaAP
        String besedilo = jTextPane2.getText();
        //System.out.println("Pap");

        String samoglasniki = "AEIOUaeiou"; 
        int dol_besedila = besedilo.length(); 
        //System.out.printf("%d\n",dol_besedila);
        int i = 0;
        int st_samo = 0; 
        char prejsnji = 'a';
        String besedilo2 = ""; // 
        while (i < dol_besedila) { // pregledamo vse znake
            //System.out.printf("%s\n",besedilo2);
            char znak = besedilo.charAt(i); // i-ti znak
            int code = (int) znak;
            if(code == 32 || code == 9 || code == 10 || code == 11 || code == 12 || code == 13){
                prejsnji = 'a';
                besedilo2 = besedilo2 + znak;
                i = i + 1;
                continue;
            }
            besedilo2 = besedilo2 + znak;// nadaljujemo novi niz iz prebranih znakov
            if (samoglasniki.indexOf(znak) != -1){
                besedilo2 = besedilo2 + "p" + prejsnji;
                prejsnji = znak;
                st_samo = st_samo + 1;
            }
            i = i + 1;
        }
        
        jTextPane2.setText(besedilo2);
        
        jLabel1.setText(OBVESTILA + "Uspešno prevedeno v Papajščino.");
    }//GEN-LAST:event_jMenuItemPapajščinaAP

    private void jTextPane2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane2KeyTyped

    private void jDialogPrekliciAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogPrekliciAP
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jDialogPrekliciAP

    private void jDialogIzhodAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogIzhodAP
        System.exit(0);
    }//GEN-LAST:event_jDialogIzhodAP

    //Boolean bg - color bacground/foreground
    private void barvajIzbrano(Color c, boolean bg) {
        StyleContext context = new StyleContext();
        Style style = context.addStyle("mystyle", null);
        if (bg) {
            StyleConstants.setBackground(style, c);
        } else {
            StyleConstants.setForeground(style, c);
        }

        jTextPane2.setCharacterAttributes(style, true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemDatotekaIzhod;
    private javax.swing.JMenuItem jMenuItemDatotekaOdpri;
    private javax.swing.JMenuItem jMenuItemDatotekaShrani;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
